---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: debian:latest
    commands:
      - chmod +x bootstrap-debian.sh bootstrap-conan.sh bootstrap.sh
      - ./bootstrap-debian.sh
      - ./bootstrap-conan.sh
      - ./bootstrap.sh
      - cd build; make -j 10