---
kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: debian:latest
    commands:
      - chmod +x bootstrap-debian.sh
      - ./bootstrap-debian.sh
      - chmod +x bootstrap-conan.sh
      - ./bootstrap-conan.sh
      - >
      cmake 
        --no-warn-unused-cli 
        -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang-11 
        -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++-11 
        -S./ -B./build 
        -G "Unix Makefiles"
      - cd build; make -j 10