target("server-main")
    set_kind("shared")
    set_basename("main")
    add_files("./**.cpp")
    set_pcxxheader("common.hpp")
    add_packages(
        "spdlog", 
        "openssl", 
        "boost", 
        "rapidjson", 
        "robin-hood-hashing", 
        "xxhash"
    )

    add_deps(
        "server-common",
        "server-database",
        "server-scripting",
        "server-api"
    )