name: Tests

on:
  push:

jobs:
  test:
    name: Test Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Install Packages
        run: |
          sudo apt update -qq -y
          chmod -x ./bootstrap-debian.sh
          sudo ./bootstrap-debian.sh
      - name: Build
        run: |
          cmake -G "Ninja" -b "build"
      - name: Compile
        run: |
          ninja -D "build"
      - name: Test
        run: |
          (cd "build/"; ctest --verbose)