name: Tests

on:
  push:

jobs:
  test:
    name: Test Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Install Packages
        run: |
          sudo apt update -qq -y
          sudo apt install -y build-essential cmake ninja-build libc6-dev libssl-dev libsqlite3-dev libcurl4-openssl-dev libboost-all-dev libpthread-stubs0-dev
      - name: Build
        run: |
          mkdir build
          (cd "build/"; cmake -G "Ninja" -DENABLE_TESTS="true" ..)
      - name: Compile
        run: |
          (cd "build/"; cmake --build . -j 1)
      - name: Test
        run: |
          (cd "build/"; ctest --verbose)