name: Tests

on:
  push:

jobs:
  test:
    name: Test Ubuntu Latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true
      - name: Install Packages
        run: |
          sudo apt update -qq -y
          sudo apt install -y wget build-essential cmake ninja-build libc6-dev libssl-dev libsqlite3-dev libcurl4-openssl-dev
      - name: Build
        run: |
          cmake -G "Ninja" -B "build"
      - name: Compile
        run: |
          ninja -D "build"
      - name: Test
        run: |
          (cd "build/"; ctest --verbose)